k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_one-financial-marketplace-dev_us-east1_gke-one-financial-marketplace-dev
  currentCluster: gke_one-financial-marketplace-dev_us-east1_gke-one-financial-marketplace-dev
  clusters:
    eita-oci:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: events
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_one-financial-marketplace-dev_us-east1_gke-one-financial-marketplace-dev:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - arch-ccs
        - default
      view:
        active: pu
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-italo
